# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f2171cf89fc83bd45b9e1824698ee6cc46250e1c7b3880a25aaa4b37e4b6153d12d29f3c049c30874923a7b58f313c1ecd571f197cf1829a77479c96af92fb4

test:
  secret_key_base: e7d95319b06af55c7c1dc091b292d292c30163eaca0d8a9e225b6d301281c0f413ac8fb76155fc2d6d3e20e815ca12503d19fb909f77cb2a2af9a8059ae0b974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
